/**
*Header File for list.c
**/

/**
*General boolean used throughout assignment
**/
typedef enum {FALSE,TRUE} BOOLEAN;

/**
*STRUCT for NODE
*index will be autogenerated and
*int value is input by user
**/
typedef struct NODE {
	int index;
	int value;
	struct NODE* nextnode;
}NODE;

/**
*STRUCT for LINKEDLIST
*Do not instantiate this struct
*use createList() to instantiate properly
**/
typedef struct LINKEDLIST {
	NODE firstnode;
	NODE *head;
	NODE *tail;
}LINKEDLIST;

/**
*Function used to create a linked list
*Input int value will be given to firstnode
*Both head and tail will start at firstnode
**/
LINKEDLIST createList(int);

/**
*This adds a node by pointer to list
*it takes the int value given
*and then creates a new node in list
*with appropriate index and value
**/
void addNode(LINKEDLIST*,int);

/**
*Prints linked list in same format
*as given file with ints
**/
void prettyPrint(LINKEDLIST*);
