#include <stdlib.h>
#include <stdio.h>
#include "list.h"

/**
*STRUCT for NODE
*index will be autogenerated and
*int value is input by user
**/
typedef struct NODE {
	int index;
	int value;
	struct NODE* nextnode;
}NODE;

/**
*Initialized node to point to
*the first node of the list and
*maintain it throughout program
*All functions point to this
*when actually changing the list
**/
NODE *aNode;

/**
*This function initializes *aNode
*if it has not beein initialized yet
*or else it fills in the first nextnode->null
*with the appropriate index and given value
**/
void add(int newvalue) {
	//This initializes list
	if(aNode == NULL) {
		NODE *first = (NODE*)malloc(sizeof(NODE));
		first->index = 0;
		first->value = newvalue;
		first->nextnode = NULL;
		aNode = first;
	}
	//This adds nodes to already initialized list
	else {
		NODE *newnode;
		NODE *tnode = aNode;

		while(tnode->nextnode != NULL) {
			tnode = tnode->nextnode;
		}
	
		newnode = (NODE*)malloc(sizeof(NODE));
		newnode->value = newvalue;
		newnode->index = tnode->index + 1; 
		newnode->nextnode = NULL;
		tnode->nextnode = newnode;
	}
}

/**
*Recursively print *aNode linked list
**/
void printNode(NODE* point) {
	printf("%d\n",point->value);
	if(point->nextnode != NULL) {
		printNode(point->nextnode);
	}
}

/**
*Prints list value from *aNode
*while maintaing list order
**/
void prettyPrint() {
	NODE *point = aNode;
	if(point != NULL) {
		printf("Current list : \n");
		printNode(point);
		printf("\n");
	}
	else {
		printf("List is empty.\n\n");
	}
}

/**
*This function returns node that is removed
*In order to keep track of nodes
*node is removed within find function
**/
NODE* find(int dvalue) {
	NODE *point = aNode;

	//This is for if trying to remove
	//a node from an empty list
	//console will print "List is empty"
	if(point == NULL) {
		return NULL;
	}

	//Find value to remove
	while(point->value != dvalue) {
		point = point->nextnode;
		if(point == NULL) {
			return NULL;
		}
	}
	//Return remove node
	return point;
}

/**
*This function actually removes node
*Mainly used to find previous node
**/
void removeNode(NODE* dnode) {
	NODE *findnode = aNode;
	//This case is for removing first node
	if(findnode == dnode) {
		aNode = findnode->nextnode;
	}
	//This case is for removing other nodes
	else {
		while(findnode->nextnode != dnode) {
			findnode = findnode->nextnode;
		}
		NODE *remove = findnode->nextnode;
		findnode->nextnode = remove->nextnode;
	}	
}

/**
*Finds and removes given value node
**/
BOOLEAN delete(int dvalue) {
	NODE *look = find(dvalue);
	if(look != NULL) {
		removeNode(look);
		return TRUE;
	}
	else {
		return FALSE;
	}
}
