/**
*Header File for list.c
**/

/**
*STRUCT for NODE
*index will be autogenerated and
*int value is input by user
**/
typedef struct NODE {
	int index;
	int value;
	struct NODE* nextnode;
}NODE;

/**
*STRUCT for LINKEDLIST
*Do not instantiate this struct
*use createList() to instantiate properly
**/
typedef struct LINKEDLIST {
	NODE firstnode;
	NODE *head;
	NODE *tail;
}LINKEDLIST;

/**
*Function used to create a linked list
*Input int value will be given to firstnode
*Both head and tail will start at firstnode
**/
LINKEDLIST createList(int);
