#include <stdlib.h>
#include <stdio.h>
#include "list.h"

/**
*STRUCT for NODE
*index will be autogenerated and
*int value is input by user
**/
typedef struct NODE {
	int index;
	int value;
	struct NODE* nextnode;
}NODE;

/**
*Initialized node to point to
*the first node of the list and
*maintain it throughout program
**/
NODE *aNode;

/**
*This function initializes *aNode
*if it has not beein initialized yet
*or else it fills in the first nextnode->null
*with the appropriate index and given value
**/
void add(int newvalue) {
	//This initializes list
	if(aNode == NULL) {
		NODE *first = (NODE*)malloc(sizeof(NODE));
		first->index = 0;
		first->value = newvalue;
		first->nextnode = NULL;
		aNode = first;
	}
	//This adds nodes to already initialized list
	else {
		NODE *newnode;
		NODE *tnode = aNode;

		while(tnode->nextnode != NULL) {
			tnode = tnode->nextnode;
		}
	
		newnode = (NODE*)malloc(sizeof(NODE));
		newnode->value = newvalue;
		newnode->index = tnode->index + 1; 
		newnode->nextnode = NULL;
		tnode->nextnode = newnode;
	}
}

/**
*Recursively print *aNode linked list
**/
void printNode(NODE* point) {
	printf("%d\n",point->value);
	if(point->nextnode != NULL) {
		printNode(point->nextnode);
	}
}

/**
*Prints list value from *aNode
*while maintaing list order
**/
void prettyPrint() {
	NODE *point = aNode;
	if(point != NULL) {
		printNode(point);
	}
	else {
		printf("List is empty.");
	}
}
